### ISSUE TITLE
Setting  metadata?

### ISSUE THREAD

**Issue by jamshid** [vmbrasseur/IAS3API#20]
Hi, just wondering how to use non-ASCII characters as metadata https://github.com/vmbrasseur/IAS3API/blob/master/metadata.md, since HTTP restricts header values to ISO-8859-1.
I guess you can use Unicode if you set metadata via files?https://github.com/vmbrasseur/IAS3API/blob/master/metadatafiles.md

**Comment by vmbrasseur** [comment]
Good question, @jamshid. I'm very surprised it hasn't come up earlier. I'll do some testing this weekend and see whether there's not another way to do this beyond using files.
